// <auto-generated />
using IS413Mission4.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IS413Mission4.Migrations
{
    [DbContext(typeof(MovieContext))]
    partial class MovieContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("IS413Mission4.Models.ApplicationResponse", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(4);

                    b.HasKey("MovieId");

                    b.ToTable("Responses");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            Category = "Action/Adventure",
                            Director = "Chris Columbus",
                            Edited = false,
                            LentTo = "Logan Kim",
                            Note = "For FHE",
                            Rating = "PG",
                            Title = "Harry Potter and the Chamber of Secrets",
                            Year = "2002"
                        },
                        new
                        {
                            MovieId = 2,
                            Category = "Action/Adventure",
                            Director = "Jon Favreau",
                            Edited = false,
                            LentTo = "Wayne Park",
                            Note = "For his dating",
                            Rating = "PG-13",
                            Title = "Iron Man",
                            Year = "2008"
                        },
                        new
                        {
                            MovieId = 3,
                            Category = "Drama",
                            Director = "Richard Curtis",
                            Edited = true,
                            LentTo = "Yes",
                            Note = "For fun",
                            Rating = "R",
                            Title = "About Time",
                            Year = "2013"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
